project:
  type: website
  output-dir: docs

website:
  title: "Adam Kong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd

format:
  html:
    theme:
      light: slate
      dark: minty
    css: styles.css
    page-layout: full

editor: visual

