project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
  search: false

format:
  html:
    theme: journal
    css: styles.css
    page-layout: article
