project:
  type: website
  output-dir: docs

website:
  title: "Adam Kong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: lux
    css: styles.css
    page-layout: full

editor: visual

