<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Kong, Cameron An">
<meta name="dcterms.date" content="2024-06-24">

<title>2023 Basketball Bayesian Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">2023 Basketball Bayesian Analysis</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Project</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Adam Kong, Cameron An </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 24, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Our research question investigates how usage rate (USG) and minutes played per game (MP) affect an NBA player’s annual salary for the 2022-23 season. Usage rate is the percentage of a team’s possessions a player ends while on the court. It’s calculated by adding up a player’s field goal attempts, turnovers, and trips to the free throw line, and then dividing that by the team’s total of those plays when the player is on the court. Minutes played per game describes how many in-game minutes (there are 48 in-game minutes in a regular NBA game) a player averages per game.</p>
<p>This data set contains numerous variables for players in the NBA. We are using USG and MP (as well as their interaction) as explanatory variables and log(Salary) as the response variable.</p>
<p>The data set includes numerous variables for NBA players during the 2022-23 season. We decided to focus on the usage rate and minutes played per game statistics and how that affects a player’s salary. The data is publicly available because players’ salaries are reported by agents and reporters and in-game stats are often released by NBA stat keepers. Kaggle (where we got the data from) compiled the data set from numerous websites and databases.</p>
<section id="pre-bayesian-analysis" class="level1">
<h1>Pre-Bayesian Analysis</h1>
<p>As seen below these explanatory variables are not very normal. However, we went into our analysis by transforming the response variable of salaries since salaries are much more likely to be skewed to the right without previous insepction of the dataset, since a few select players will have extreme salaries.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Possible transformations and inspection of data before analysis.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="proposed-bayesian-model" class="level1">
<h1>Proposed Bayesian Model</h1>
<p><span class="math display">\[{\log(Y)} = {\beta_0} + {\beta_1}(USG) + {\beta_2}(MP) + {\beta_3}(USG*MP) + {\varepsilon}\]</span></p>
</section>
<section id="choice-of-likelihood" class="level1">
<h1>Choice of Likelihood</h1>
<p>We used a Normal likelihood to calculate the probability of observing a certain log(Salary) given certain parameters for the betas.</p>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<p>Linearity: The relationship between log(Salary) and the explanatory variables is linear Homoscedasticity: variance of the residuals is constant Independence of errors: Residuals are independent of each other Normally distributed: Residuals are approximately normally distributed Independence of independent variables: included interaction effect in model to see how variables interact with each other.</p>
</section>
<section id="bayesian-model-analysis" class="level1">
<h1>Bayesian Model Analysis</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ MP + USG. + MP * USG., data = nba_salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.8611 -0.5311  0.2033  0.7138  2.7588 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 14.1414029  0.3791128  37.301  &lt; 2e-16 ***
MP           0.0272010  0.0179315   1.517   0.1300    
USG.        -0.0485190  0.0197029  -2.463   0.0142 *  
MP:USG.      0.0033111  0.0008146   4.065 5.65e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.191 on 463 degrees of freedom
Multiple R-squared:  0.4103,    Adjusted R-squared:  0.4064 
F-statistic: 107.4 on 3 and 463 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We used BRMS to choose a prior distribution for the data. The model chose a student_t(3, 15.1, 2.5) distribution for the intercept and a student_t(3, 0, 2.5) distribution for sigma. The MP and USG variables have a flat prior, which is an improper distribution, but one that makes no assumption of the distribution.</p>
</section>
<section id="brms-chosen-prior" class="level1">
<h1>BRMS Chosen Prior</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                   prior     class    coef group resp dpar nlpar lb ub
                  (flat)         b                                    
                  (flat)         b      MP                            
                  (flat)         b MP:USG.                            
                  (flat)         b    USG.                            
 student_t(3, 15.1, 2.5) Intercept                                    
    student_t(3, 0, 2.5)     sigma                                0   
       source
      default
 (vectorized)
 (vectorized)
 (vectorized)
      default
      default</code></pre>
</div>
</div>
</section>
<section id="brms-first-model" class="level1">
<h1>BRMS (First Model)</h1>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Compiling Stan program...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Start sampling</code></pre>
</div>
</div>
</section>
<section id="brms-posterior-output-analysis" class="level1">
<h1>BRMS Posterior Output Analysis</h1>
<p>The posterior distribution does not change very much if the prior changes. This is because we have a large sample size for our data, which means that the data is going to hold the most weight in the posterior distribution.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: log(Salary) ~ MP + USG. + MP * USG. 
   Data: nba_salary (Number of observations: 467) 
  Draws: 4 chains, each with iter = 3500; warmup = 1000; thin = 1;
         total post-warmup draws = 10000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    14.14      0.38    13.38    14.88 1.00     4292     4899
MP            0.03      0.02    -0.01     0.06 1.00     4641     5394
USG.         -0.05      0.02    -0.09    -0.01 1.00     4516     5659
MP:USG.       0.00      0.00     0.00     0.00 1.00     4291     5334

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     1.19      0.04     1.12     1.27 1.00     6202     6083

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>Note, that we did run an interaction between minutes played and player usage. We decided to keep that in when simulated because before simulation we found that the interaction was significant, but now it was not in the posterior. We did not find this out until after the simulation was ran, but we kept because it’s notable that minutes played and usage, while correlated, it’s interaction was not significant to the log salary.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Simulated distributions follow a similar distribution with the actual curve. The actual curve has some strange curves due to the salary.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this plot we can see that minutes played has a positive correlation with the usage rate. This is expected as generally players with a high minutes played will have a larger usage rate.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking good so far! The chains are very close to each other here.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>b_Intercept        b_MP      b_USG.       sigma 
  0.4291956   0.4640683   0.4516122   0.6083066 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looks good.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>MP is a positive coefficent, just like before the simulation.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Possibly may have some negative simulated values, but more positive.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Surprisingly the coefficient for Usage is negative. Not very strong as usage has a range from 0 to 100, and most players have below 50 so not as big of an effect.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> b_Intercept </th>
   <th style="text-align:right;"> sigma </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.40485 </td>
   <td style="text-align:right;"> 1.204247 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.34406 </td>
   <td style="text-align:right;"> 1.219551 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 15.02886 </td>
   <td style="text-align:right;"> 1.152280 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.75198 </td>
   <td style="text-align:right;"> 1.173161 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.99844 </td>
   <td style="text-align:right;"> 1.188551 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 14.09294 </td>
   <td style="text-align:right;"> 1.199925 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 14.02182 </td>
   <td style="text-align:right;"> 1.157511 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.98063 </td>
   <td style="text-align:right;"> 1.149257 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 14.03309 </td>
   <td style="text-align:right;"> 1.133600 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.97693 </td>
   <td style="text-align:right;"> 1.207306 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> Intercept_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.40485 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.34406 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 15.02886 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.75198 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.99844 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 14.09294 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 14.02182 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.98063 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 14.03309 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.97693 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> sigma_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1.204247 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1.219551 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1.152280 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1.173161 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 1.188551 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 1.199925 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 1.157511 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1.149257 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 1.133600 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1.207306 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="posterior-population-analysis" class="level1">
<h1>Posterior Population Analysis</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      10%      25%      50%      75%      90%      99% 
13.27517 13.64588 13.88557 14.13771 14.39287 14.62084 15.02537 </code></pre>
</div>
</div>
<p>There is a 50% chance that the population mean salary is between <span class="math inline">\(e^{13.87}\)</span> and <span class="math inline">\(e^{14.38}\)</span> dollars. There is an 80% chance that the population mean salary is between <span class="math inline">\(e^{13.63}\)</span> and <span class="math inline">\(e^{14.64}\)</span> dollars. There is a 98% chance that the population mean salary is between <span class="math inline">\(e^{13.23}\)</span> and <span class="math inline">\(e^{15.04}\)</span> dollars.</p>
<p><span class="math inline">\(e^{13.23}\)</span> is roughly around 556,821.5 dollars and <span class="math inline">\(e^{15.04}\)</span> is roughly around 3,402,429 dollars</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      10%      25%      50%      75%      90%      99% 
1.110284 1.145708 1.167242 1.193142 1.219245 1.243345 1.286354 </code></pre>
</div>
</div>
<p>There is a 50% chance that the population SD of salary is between <span class="math inline">\(e^{1.17}\)</span> and <span class="math inline">\(e^{1.22}\)</span> dollars. There is an 80% chance that the population SD of salary is between <span class="math inline">\(e^{1.14}\)</span> and <span class="math inline">\(e^{1.25}\)</span> dollars. There is an 98% chance that the population SD of salary is between <span class="math inline">\(e^{1.11}\)</span> and <span class="math inline">\(e^{1.29}\)</span> dollars.</p>
<p><span class="math inline">\(e^{1.11}\)</span> is roughly around 3.03 dollars and <span class="math inline">\(e^{1.29}\)</span> is roughly around 3.63 dollars. This is a little strange, but since we transformed our response, the standard deviation likely wasn’t as varied transformed.</p>
</section>
<section id="stephen-curry-posterior-analysis-model-1" class="level1">
<h1>Stephen Curry Posterior Analysis (Model 1)</h1>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> b_Intercept </th>
   <th style="text-align:right;"> b_MP </th>
   <th style="text-align:right;"> b_USG. </th>
   <th style="text-align:right;"> b_MP:USG. </th>
   <th style="text-align:right;"> sigma </th>
   <th style="text-align:right;"> Steph_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.40485 </td>
   <td style="text-align:right;"> 0.0548780 </td>
   <td style="text-align:right;"> -0.0062152 </td>
   <td style="text-align:right;"> 0.0017695 </td>
   <td style="text-align:right;"> 1.204247 </td>
   <td style="text-align:right;"> 17.01991 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.34406 </td>
   <td style="text-align:right;"> 0.0545617 </td>
   <td style="text-align:right;"> 0.0015346 </td>
   <td style="text-align:right;"> 0.0015706 </td>
   <td style="text-align:right;"> 1.219551 </td>
   <td style="text-align:right;"> 16.97440 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 15.02886 </td>
   <td style="text-align:right;"> -0.0244940 </td>
   <td style="text-align:right;"> -0.0892599 </td>
   <td style="text-align:right;"> 0.0056076 </td>
   <td style="text-align:right;"> 1.152280 </td>
   <td style="text-align:right;"> 17.44392 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.75198 </td>
   <td style="text-align:right;"> 0.0045300 </td>
   <td style="text-align:right;"> -0.0867470 </td>
   <td style="text-align:right;"> 0.0047307 </td>
   <td style="text-align:right;"> 1.173161 </td>
   <td style="text-align:right;"> 17.30883 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.99844 </td>
   <td style="text-align:right;"> 0.0155831 </td>
   <td style="text-align:right;"> -0.0408150 </td>
   <td style="text-align:right;"> 0.0035912 </td>
   <td style="text-align:right;"> 1.188551 </td>
   <td style="text-align:right;"> 17.13699 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 14.09294 </td>
   <td style="text-align:right;"> 0.0178233 </td>
   <td style="text-align:right;"> -0.0452517 </td>
   <td style="text-align:right;"> 0.0035047 </td>
   <td style="text-align:right;"> 1.199925 </td>
   <td style="text-align:right;"> 17.07861 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 14.02182 </td>
   <td style="text-align:right;"> 0.0404170 </td>
   <td style="text-align:right;"> -0.0481537 </td>
   <td style="text-align:right;"> 0.0028471 </td>
   <td style="text-align:right;"> 1.157511 </td>
   <td style="text-align:right;"> 16.99415 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.98063 </td>
   <td style="text-align:right;"> 0.0323411 </td>
   <td style="text-align:right;"> -0.0431461 </td>
   <td style="text-align:right;"> 0.0030347 </td>
   <td style="text-align:right;"> 1.149257 </td>
   <td style="text-align:right;"> 17.02974 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 14.03309 </td>
   <td style="text-align:right;"> 0.0182546 </td>
   <td style="text-align:right;"> -0.0363864 </td>
   <td style="text-align:right;"> 0.0034585 </td>
   <td style="text-align:right;"> 1.133600 </td>
   <td style="text-align:right;"> 17.25890 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.97693 </td>
   <td style="text-align:right;"> 0.0369747 </td>
   <td style="text-align:right;"> -0.0420919 </td>
   <td style="text-align:right;"> 0.0029937 </td>
   <td style="text-align:right;"> 1.207306 </td>
   <td style="text-align:right;"> 17.17546 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      10%      25%      50%      75%      90%      99% 
16.74413 16.92391 17.02689 17.14147 17.25778 17.36358 17.54615 </code></pre>
</div>
</div>
<p>There is a 50% chance that the salary of a player with Stephen Curry’s USG and MP is between <span class="math inline">\(e^{17.031}\)</span> and <span class="math inline">\(e^{17.258}\)</span> dollars. There is an 80% chance that the salary of a player with Stephen Curry’s USG and MP is between <span class="math inline">\(e^{16.926}\)</span> and <span class="math inline">\(e^{17.361}\)</span> dollars. There is a 98% chance that the salary of a player with Stephen Curry’s USG and MP is between <span class="math inline">\(e^{16.747}\)</span> and <span class="math inline">\(e^{17.533}\)</span> dollars.</p>
<p>In other words for the 98% credible interval, there is a 98% chance that the salary of a player with Stephen Curry’s USG and MP is between 18,755,545 and 41,160,927 dollars. This is a really accurate prediction, especially since Stephen Curry’s salaries is the highest in the data set.</p>
</section>
<section id="davion-mitchell-posterior-analysis-model-1" class="level1">
<h1>Davion Mitchell Posterior Analysis (Model 1)</h1>
<p>We then inspected a player in the middle of the list, Davion Mitchell who plays a decent amount of games and is a reasonably average NBA player to analyze.</p>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> b_Intercept </th>
   <th style="text-align:right;"> b_MP </th>
   <th style="text-align:right;"> b_USG. </th>
   <th style="text-align:right;"> b_MP:USG. </th>
   <th style="text-align:right;"> sigma </th>
   <th style="text-align:right;"> Davion_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.40485 </td>
   <td style="text-align:right;"> 0.0548780 </td>
   <td style="text-align:right;"> -0.0062152 </td>
   <td style="text-align:right;"> 0.0017695 </td>
   <td style="text-align:right;"> 1.204247 </td>
   <td style="text-align:right;"> 14.75941 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.34406 </td>
   <td style="text-align:right;"> 0.0545617 </td>
   <td style="text-align:right;"> 0.0015346 </td>
   <td style="text-align:right;"> 0.0015706 </td>
   <td style="text-align:right;"> 1.219551 </td>
   <td style="text-align:right;"> 14.84746 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 15.02886 </td>
   <td style="text-align:right;"> -0.0244940 </td>
   <td style="text-align:right;"> -0.0892599 </td>
   <td style="text-align:right;"> 0.0056076 </td>
   <td style="text-align:right;"> 1.152280 </td>
   <td style="text-align:right;"> 14.36750 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.75198 </td>
   <td style="text-align:right;"> 0.0045300 </td>
   <td style="text-align:right;"> -0.0867470 </td>
   <td style="text-align:right;"> 0.0047307 </td>
   <td style="text-align:right;"> 1.173161 </td>
   <td style="text-align:right;"> 14.19449 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.99844 </td>
   <td style="text-align:right;"> 0.0155831 </td>
   <td style="text-align:right;"> -0.0408150 </td>
   <td style="text-align:right;"> 0.0035912 </td>
   <td style="text-align:right;"> 1.188551 </td>
   <td style="text-align:right;"> 14.52262 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 14.09294 </td>
   <td style="text-align:right;"> 0.0178233 </td>
   <td style="text-align:right;"> -0.0452517 </td>
   <td style="text-align:right;"> 0.0035047 </td>
   <td style="text-align:right;"> 1.199925 </td>
   <td style="text-align:right;"> 14.47335 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 14.02182 </td>
   <td style="text-align:right;"> 0.0404170 </td>
   <td style="text-align:right;"> -0.0481537 </td>
   <td style="text-align:right;"> 0.0028471 </td>
   <td style="text-align:right;"> 1.157511 </td>
   <td style="text-align:right;"> 14.34340 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.98063 </td>
   <td style="text-align:right;"> 0.0323411 </td>
   <td style="text-align:right;"> -0.0431461 </td>
   <td style="text-align:right;"> 0.0030347 </td>
   <td style="text-align:right;"> 1.149257 </td>
   <td style="text-align:right;"> 14.42557 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 14.03309 </td>
   <td style="text-align:right;"> 0.0182546 </td>
   <td style="text-align:right;"> -0.0363864 </td>
   <td style="text-align:right;"> 0.0034585 </td>
   <td style="text-align:right;"> 1.133600 </td>
   <td style="text-align:right;"> 14.67423 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.97693 </td>
   <td style="text-align:right;"> 0.0369747 </td>
   <td style="text-align:right;"> -0.0420919 </td>
   <td style="text-align:right;"> 0.0029937 </td>
   <td style="text-align:right;"> 1.207306 </td>
   <td style="text-align:right;"> 14.50199 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      10%      25%      50%      75%      90%      99% 
14.04659 14.23934 14.34862 14.47095 14.58620 14.69532 14.86884 </code></pre>
</div>
</div>
<p>There is a 50% chance that the salary of a player with Davion Mitchell’s USG and MP is between <span class="math inline">\(e^{14.354}\)</span> and <span class="math inline">\(e^{14.590}\)</span> dollars. There is an 80% chance that the salary of a player with Davion Mitchell’s USG and MP is between <span class="math inline">\(e^{14.250}\)</span> and <span class="math inline">\(e^{14.698}\)</span> dollars. There is a 98% chance that the salary of a player with Davion Mitchell’s USG and MP is between <span class="math inline">\(e^{14.070}\)</span> and <span class="math inline">\(e^{14.866}\)</span> dollars.</p>
<p>For the 98% credible interval, there is a 98% chance that the salary of a player with Davion Mitchell’s USG and MP is between 1,289,803 and 2,859,050 dollars. This is a pretty accurate prediction to his actual salary.</p>
</section>
<section id="brms-model-2" class="level1">
<h1>BRMS (Model 2)</h1>
<p>We did another analysis below for both Stephen Curry and Davion Mitchell. We saw that Davion Mitchell had a lot more games played than Stephen Curry but had significantly lower pay. We wanted to see if games played had more of an effect on players like Davion, but would not players with higher stats like Curry.</p>
<p>Will only look at the 98% credible interval for this analysis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ MP + USG. + GP + MP * USG., data = nba_salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.8219 -0.6882  0.0414  0.6706  3.6089 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.7403724  0.3433410  40.020  &lt; 2e-16 ***
MP          -0.0377184  0.0172884  -2.182   0.0296 *  
USG.        -0.0441375  0.0177373  -2.488   0.0132 *  
GP           0.0278838  0.0026632  10.470  &lt; 2e-16 ***
MP:USG.      0.0039952  0.0007361   5.428 9.24e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.072 on 462 degrees of freedom
Multiple R-squared:  0.5233,    Adjusted R-squared:  0.5192 
F-statistic: 126.8 on 4 and 462 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Compiling Stan program...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Start sampling</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: log(Salary) ~ MP + USG. + GP + MP * USG. 
   Data: nba_salary (Number of observations: 467) 
  Draws: 4 chains, each with iter = 3500; warmup = 1000; thin = 1;
         total post-warmup draws = 10000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    13.74      0.35    13.08    14.44 1.00     5001     6077
MP           -0.04      0.02    -0.07    -0.00 1.00     4934     6130
USG.         -0.04      0.02    -0.08    -0.01 1.00     5182     5735
GP            0.03      0.00     0.02     0.03 1.00     9039     6536
MP:USG.       0.00      0.00     0.00     0.01 1.00     4958     6196

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     1.08      0.04     1.01     1.15 1.00     5666     5261

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A little more off than model 1 ppcheck.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this plot we can see that minutes played still has a positive correlation with the usage rate. Both minutes played and usage rate is independent of games played.</p>
</section>
<section id="stephen-curry-posterior-analysis-model-2" class="level1">
<h1>Stephen Curry Posterior Analysis (Model 2)</h1>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> b_Intercept </th>
   <th style="text-align:right;"> b_MP </th>
   <th style="text-align:right;"> b_USG. </th>
   <th style="text-align:right;"> b_GP </th>
   <th style="text-align:right;"> b_MP:USG. </th>
   <th style="text-align:right;"> sigma </th>
   <th style="text-align:right;"> Steph_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.48283 </td>
   <td style="text-align:right;"> -0.0280019 </td>
   <td style="text-align:right;"> -0.0218425 </td>
   <td style="text-align:right;"> 0.0275287 </td>
   <td style="text-align:right;"> 0.0031478 </td>
   <td style="text-align:right;"> 1.105768 </td>
   <td style="text-align:right;"> 16.76171 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.52880 </td>
   <td style="text-align:right;"> -0.0241469 </td>
   <td style="text-align:right;"> -0.0386563 </td>
   <td style="text-align:right;"> 0.0289255 </td>
   <td style="text-align:right;"> 0.0033301 </td>
   <td style="text-align:right;"> 1.073317 </td>
   <td style="text-align:right;"> 16.69455 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 13.58264 </td>
   <td style="text-align:right;"> -0.0403084 </td>
   <td style="text-align:right;"> -0.0344208 </td>
   <td style="text-align:right;"> 0.0270341 </td>
   <td style="text-align:right;"> 0.0041277 </td>
   <td style="text-align:right;"> 1.072027 </td>
   <td style="text-align:right;"> 17.07094 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.04728 </td>
   <td style="text-align:right;"> -0.0512499 </td>
   <td style="text-align:right;"> -0.0657865 </td>
   <td style="text-align:right;"> 0.0273223 </td>
   <td style="text-align:right;"> 0.0049092 </td>
   <td style="text-align:right;"> 1.083099 </td>
   <td style="text-align:right;"> 17.04040 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.55265 </td>
   <td style="text-align:right;"> -0.0387647 </td>
   <td style="text-align:right;"> -0.0306456 </td>
   <td style="text-align:right;"> 0.0302348 </td>
   <td style="text-align:right;"> 0.0035624 </td>
   <td style="text-align:right;"> 1.075760 </td>
   <td style="text-align:right;"> 16.78275 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 13.40052 </td>
   <td style="text-align:right;"> -0.0267959 </td>
   <td style="text-align:right;"> -0.0228545 </td>
   <td style="text-align:right;"> 0.0294279 </td>
   <td style="text-align:right;"> 0.0031389 </td>
   <td style="text-align:right;"> 1.068282 </td>
   <td style="text-align:right;"> 16.78670 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 13.06423 </td>
   <td style="text-align:right;"> -0.0245535 </td>
   <td style="text-align:right;"> -0.0150045 </td>
   <td style="text-align:right;"> 0.0319892 </td>
   <td style="text-align:right;"> 0.0031422 </td>
   <td style="text-align:right;"> 1.074816 </td>
   <td style="text-align:right;"> 16.91849 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.78238 </td>
   <td style="text-align:right;"> -0.0338930 </td>
   <td style="text-align:right;"> -0.0551842 </td>
   <td style="text-align:right;"> 0.0239274 </td>
   <td style="text-align:right;"> 0.0043828 </td>
   <td style="text-align:right;"> 1.049268 </td>
   <td style="text-align:right;"> 16.95010 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 13.83966 </td>
   <td style="text-align:right;"> -0.0429355 </td>
   <td style="text-align:right;"> -0.0516866 </td>
   <td style="text-align:right;"> 0.0286253 </td>
   <td style="text-align:right;"> 0.0043719 </td>
   <td style="text-align:right;"> 1.077175 </td>
   <td style="text-align:right;"> 17.05337 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.82837 </td>
   <td style="text-align:right;"> -0.0422647 </td>
   <td style="text-align:right;"> -0.0483255 </td>
   <td style="text-align:right;"> 0.0272944 </td>
   <td style="text-align:right;"> 0.0044127 </td>
   <td style="text-align:right;"> 1.076766 </td>
   <td style="text-align:right;"> 17.13896 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      99% 
16.55984 17.27935 </code></pre>
</div>
</div>
<p>There is a 98% chance that the salary of a player with Stephen Curry’s USG, MP, and GP is between <span class="math inline">\(e^{16.56}\)</span> and <span class="math inline">\(e^{17.29}\)</span> dollars.</p>
<p>There is a 98% chance that a player with Stephen Curry’s stats will have a predicted salary of 15,556,669 to 32,130,940 dollars. This seems more incorrect as Curry has a salary closer to 40 million dollars, but reasonable when it comes to number of games played. Curry is an outlier in terms of salary, so this prediction makes sense.</p>
</section>
<section id="davion-mitchell-posterior-analysis-model-2" class="level1">
<h1>Davion Mitchell Posterior Analysis (Model 2)</h1>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> .chain </th>
   <th style="text-align:right;"> .iteration </th>
   <th style="text-align:right;"> .draw </th>
   <th style="text-align:right;"> b_Intercept </th>
   <th style="text-align:right;"> b_MP </th>
   <th style="text-align:right;"> b_USG. </th>
   <th style="text-align:right;"> b_GP </th>
   <th style="text-align:right;"> b_MP:USG. </th>
   <th style="text-align:right;"> sigma </th>
   <th style="text-align:right;"> Davion_y </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 13.48283 </td>
   <td style="text-align:right;"> -0.0280019 </td>
   <td style="text-align:right;"> -0.0218425 </td>
   <td style="text-align:right;"> 0.0275287 </td>
   <td style="text-align:right;"> 0.0031478 </td>
   <td style="text-align:right;"> 1.105768 </td>
   <td style="text-align:right;"> 15.98907 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 13.52880 </td>
   <td style="text-align:right;"> -0.0241469 </td>
   <td style="text-align:right;"> -0.0386563 </td>
   <td style="text-align:right;"> 0.0289255 </td>
   <td style="text-align:right;"> 0.0033301 </td>
   <td style="text-align:right;"> 1.073317 </td>
   <td style="text-align:right;"> 15.75960 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 13.58264 </td>
   <td style="text-align:right;"> -0.0403084 </td>
   <td style="text-align:right;"> -0.0344208 </td>
   <td style="text-align:right;"> 0.0270341 </td>
   <td style="text-align:right;"> 0.0041277 </td>
   <td style="text-align:right;"> 1.072027 </td>
   <td style="text-align:right;"> 15.91418 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 14.04728 </td>
   <td style="text-align:right;"> -0.0512499 </td>
   <td style="text-align:right;"> -0.0657865 </td>
   <td style="text-align:right;"> 0.0273223 </td>
   <td style="text-align:right;"> 0.0049092 </td>
   <td style="text-align:right;"> 1.083099 </td>
   <td style="text-align:right;"> 15.61687 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 13.55265 </td>
   <td style="text-align:right;"> -0.0387647 </td>
   <td style="text-align:right;"> -0.0306456 </td>
   <td style="text-align:right;"> 0.0302348 </td>
   <td style="text-align:right;"> 0.0035624 </td>
   <td style="text-align:right;"> 1.075760 </td>
   <td style="text-align:right;"> 16.03197 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 13.40052 </td>
   <td style="text-align:right;"> -0.0267959 </td>
   <td style="text-align:right;"> -0.0228545 </td>
   <td style="text-align:right;"> 0.0294279 </td>
   <td style="text-align:right;"> 0.0031389 </td>
   <td style="text-align:right;"> 1.068282 </td>
   <td style="text-align:right;"> 16.04046 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 13.06423 </td>
   <td style="text-align:right;"> -0.0245535 </td>
   <td style="text-align:right;"> -0.0150045 </td>
   <td style="text-align:right;"> 0.0319892 </td>
   <td style="text-align:right;"> 0.0031422 </td>
   <td style="text-align:right;"> 1.074816 </td>
   <td style="text-align:right;"> 16.18546 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 13.78238 </td>
   <td style="text-align:right;"> -0.0338930 </td>
   <td style="text-align:right;"> -0.0551842 </td>
   <td style="text-align:right;"> 0.0239274 </td>
   <td style="text-align:right;"> 0.0043828 </td>
   <td style="text-align:right;"> 1.049268 </td>
   <td style="text-align:right;"> 15.42370 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 13.83966 </td>
   <td style="text-align:right;"> -0.0429355 </td>
   <td style="text-align:right;"> -0.0516866 </td>
   <td style="text-align:right;"> 0.0286253 </td>
   <td style="text-align:right;"> 0.0043719 </td>
   <td style="text-align:right;"> 1.077175 </td>
   <td style="text-align:right;"> 15.83296 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 13.82837 </td>
   <td style="text-align:right;"> -0.0422647 </td>
   <td style="text-align:right;"> -0.0483255 </td>
   <td style="text-align:right;"> 0.0272944 </td>
   <td style="text-align:right;"> 0.0044127 </td>
   <td style="text-align:right;"> 1.076766 </td>
   <td style="text-align:right;"> 15.84671 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1%      99% 
15.34250 16.28187 </code></pre>
</div>
</div>
<p>There is a 98% chance that the salary of a player with Davion Mitchell’s USG, MP, and GP is between <span class="math inline">\(e^{15.35}\)</span> and <span class="math inline">\(e^{16.28}\)</span> dollars.</p>
<p>In other words, there is a 98% chance that a player with Davion Mitchell’s stats will have a predicted salary of 4,638,956 to 11,757,478 dollars. This seems more incorrect as Mitchell has a salary closer to 1 million dollars. Games played doesn’t mean a player gets paid more, but this model will over predicted players who have been in a lot of games. Davion Mitchell is an outlier in terms of the games played.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Based on the credible intervals we obtained, our model only using minutes played and usage rate produces a closer prediction to the actual salary values. After including games played in our model, our predictions fell further from the actual numbers. Although, we attempted to include more variables, our predictions became more off because these variables don’t describe salary behavior as well.</p>
<p>One shortcoming we saw of our chosen model is that it isn’t not highly descriptive and doesn’t a describe the wide range of individual player statistics. For example is that certain players will have a lot of minutes played per game, has a high usage rate, but only one game played and not be paid over one million dollars. Their salary will be over predicted.</p>
<p>There is one point in Handout 27 Model Comparison that Professor Ross points out about a simple model versus a complex model. “However, we don’t always want to just choose the more complex model. Always choosing the more complex model over fits the data.” As we saw with our more complex model which included games played, it did over fit Davion Mitchell’s salary significance, despite being considered what would be an average player with an average players stats. So for this analysis we focused on minutes played (MP) and usage rate (USG), since we believed salaries would be affected the most significantly by these statistics and would describe salaries within the data set the best.</p>
<p>One thing we considered while concluding this report is the popularity of each player that was not mentioned in this data set. Many increases in salaries include outside variables such as endorsements, brand deals, and other marketability each player has. Player statistics is one aspect of salary, but outside influence could have much more effect and should be furthered analyzed.</p>
<p>Relating and concluding our research with the Bayesian perspective, we found that our Bayesian analysis was valuable in our context since the salaries of players are constantly changing every season. It would be inaccurate to state our parameters without looking at the data. This Bayesian analysis approach allowed us to account for the always-changing landscape of basketball salaries.</p>
</section>
<section id="brms-untransformed-response-model" class="level1">
<h1>BRMS Untransformed Response Model</h1>
<p>Down below is our first model with no transformation. Although this model could be used, we found that a normal distribution in BRMS would’ve lead to an easier interpretation.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Compiling Stan program...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Start sampling</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: exponential 
  Links: mu = log 
Formula: Salary ~ MP + USG. 
   Data: nba_salary (Number of observations: 467) 
  Draws: 4 chains, each with iter = 3500; warmup = 1000; thin = 1;
         total post-warmup draws = 10000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    13.36      0.16    13.04    13.67 1.00    10679     7907
MP            0.09      0.01     0.08     0.10 1.00     7050     6932
USG.          0.02      0.01     0.00     0.04 1.00     6878     6893

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Similarly, simulated distributions follow a similar distribution with the actual curve. But again, the actual curve has some strange curves due to the salary.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: exponential 
  Links: mu = log 
Formula: Salary ~ MP + USG. 
   Data: nba_salary (Number of observations: 467) 
  Draws: 4 chains, each with iter = 3500; warmup = 1000; thin = 1;
         total post-warmup draws = 10000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    13.36      0.16    13.04    13.67 1.00    10679     7907
MP            0.09      0.01     0.08     0.10 1.00     7050     6932
USG.          0.02      0.01     0.00     0.04 1.00     6878     6893

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>